language: python

notifications:
      email: false

python:
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - sudo apt install graphviz graphviz-dev

script:
    - pip install .
    - cd test
    - pip install -r requirements.txt
    - pytest -v test_graphs.py
