language: python

notifications:
      email: false

python:
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - sudo apt install graphviz graphviz-dev

script:
    - pip install .
    - cd test
    - pip install -r requirements.txt
    - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install black; black --check . ../graphviz2drawio; fi
    - pytest -v test_graphs.py
